version: '1.0.0'

services:
  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 3001:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: http://localhost:8080

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost

  playwright:
    build:
      dockerfile: ./playwright/Dockerfile
    env_file:
      - .env
    links:
      - ghost:ghost
    ports:
      - 8080:8080
