version: '1.0.0'

services:
  ghost-playwright-4489:
    image: ghost:4.48.9
    restart: always
    ports:
      - 8080:2368
    depends_on:
      - db-ghost-playwright-4489
    environment:
      database__client: mysql
      database__connection__host: db-ghost-playwright-4489
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: http://localhost:8080
    networks:
      - ghost-playwright

  db-ghost-playwright-4489:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    networks:
      - ghost-playwright

  playwright:
    build:
      dockerfile: ./playwright/Dockerfile
    env_file:
      - .env
    depends_on:
      - ghost-playwright
    ports:
      - 9323:9323
    environment:
      BASE_URL: ${BASE_URL}
    networks:
      - ghost-playwright

  ##########################################

  ghost-playwright-4380:
    image: ghost:4.38.0
    restart: always
    ports:
      - 8081:2368
    depends_on:
      - db-kraken
    environment:
      database__client: mysql
      database__connection__host: db-kraken
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: http://localhost:8081
    networks:
      - ghost-playwright

  db-ghost-playwright-4380:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    networks:
      - ghost-playwright

  ghost-kraken-4480:
    image: ghost:4.48.9
    restart: always
    ports:
      - 8090:2368
    depends_on:
      - db-kraken
    environment:
      database__client: mysql
      database__connection__host: db-kraken
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: http://localhost:8090
    networks:
      - ghost-kraken

  ghost-kraken-4380:
    image: ghost:4.38.0
    restart: always
    ports:
      - 8091:2368
    depends_on:
      - db-kraken
    environment:
      database__client: mysql
      database__connection__host: db-kraken
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: http://localhost:8091
    networks:
      - ghost-kraken

  db-kraken:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    networks:
      - ghost-kraken

networks:
  ghost-kraken:
    driver: bridge
  ghost-playwright:
    driver: bridge
  ghost-playwright-4480:
    driver: bridge
