version: '1.0.0'

services:
  ghost-playwright:
    image: ghost:4.38.0
    restart: always
    ports:
      - 8080:2368
    depends_on:
      - db-playwright
    environment:
      database__client: mysql
      database__connection__host: db-playwright
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      NODE_ENV: production
      url: http://localhost:8080
    networks:
      - ghost-playwright

  db-playwright:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    networks:
      - ghost-playwright

networks:
  ghost-playwright:
    driver: bridge
