version: '1.0.0'

services:
  ghost-kraken:
    image: ghost:4.48.9
    restart: always
    ports:
      - 8080:2368
    depends_on:
      - db-kraken
    environment:
      database__client: mysql
      database__connection__host: db-kraken
      database__connection__user: root
      database__connection__password: ghost
      database__connection__database: ghost
      url: http://localhost:2368
    networks:
      - ghost-kraken

  db-kraken:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ghost
    networks:
      - ghost-kraken

networks:
  ghost-kraken:
    driver: bridge
