import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:2368/ghost/');
  await page.goto('http://localhost:2368/ghost/#/signin');
  await page.getByPlaceholder('jamie@example.com').click();
  await page.getByPlaceholder('jamie@example.com').fill('admin@admin.com');
  await page.getByPlaceholder('•••••••••••••••').click();
  await page.getByPlaceholder('•••••••••••••••').fill('AdminAndes1**');
  await page.getByRole('button', { name: 'Sign in →' }).click();
  await page.getByRole('link', { name: 'Pages' }).click();
  await page.getByRole('link', { name: 'New page' }).click();
  await page.getByPlaceholder('Page title').click();
  await page.getByPlaceholder('Page title').fill('test');
  await page.getByPlaceholder('Page title').press('Tab');
  await page.getByRole('button', { name: 'Publish' }).click();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('button', { name: 'Settings' }).click();
  await page.getByRole('button', { name: 'Delete page' }).click();
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await page.getByRole('link', { name: 'New page' }).click();
  await page.getByPlaceholder('Page title').click();
  await page.getByPlaceholder('Page title').fill('test');
  await page.getByPlaceholder('Page title').press('Tab');
  await page.getByRole('button', { name: 'Publish' }).click();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('button', { name: 'Settings' }).click();
  await page.getByText('localhost:2368/test/').click();
  await page1.goto('http://localhost:2368/test/');
  await page1.getByRole('heading', { name: 'test' }).click();
  await page.getByRole('button', { name: 'Delete page' }).click();
  await page.getByRole('button', { name: 'Delete', exact: true }).click();
  await page1.getByRole('heading', { name: '404' }).click();
});