import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:2368/ghost/');
  await page.goto('http://localhost:2368/ghost/#/signin');
  await page.getByPlaceholder('jamie@example.com').click();
  await page.getByPlaceholder('jamie@example.com').fill('admin@admin.com');
  await page.getByPlaceholder('jamie@example.com').press('Tab');
  await page.getByPlaceholder('•••••••••••••••').fill('AdminAndes1**');
  await page.getByRole('button', { name: 'Sign in →' }).click();
  await page.getByRole('link', { name: 'Members 1' }).click();
  await page.getByRole('link', { name: 'New member' }).click();
  await page.getByLabel('Name').click();
  await page.getByLabel('Name').fill('test');
  await page.getByLabel('Email').dblclick();
  await page.getByLabel('Email').fill('test@gmail.com');
  await page.locator('#ember-power-select-trigger-multiple-input-ember92').fill('t');
  await page.locator('#ember91').getByRole('button').click();
  await page.locator('#ember-power-select-trigger-multiple-input-ember92').fill('test');
  await page.getByLabel('Note (not visible to member)').click();
  await page.getByLabel('Note (not visible to member)').fill('test');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByLabel('Note (not visible to member)').dblclick();
  await page.getByLabel('Name').click();
  await page.getByRole('button', { name: 'Retry' }).click();
  await page.getByRole('button', { name: 'Retry' }).click();
  await page.getByLabel('Email').dblclick();
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').press('ArrowLeft');
  await page.getByLabel('Email').fill('test@gmail123.com');
  await page.getByRole('button', { name: 'Retry' }).click();
  await page.getByRole('link', { name: 'Members 1' }).click();
  await page.getByRole('link', { name: 'testtestest test@gmail123.com' }).click();
  await page.getByRole('heading', { name: 'testtestest', exact: true }).click();
  await page.getByRole('link', { name: 'test@gmail123.com' }).click();
});